executor: LocalExecutor

airflowVersion: "2.11.0"
defaultAirflowTag: "2.11.0"

webserverSecretKeySecretName: airflow-webserver-secret-key
webserverSecretKeySecretKey: webserver-secret-key

createUserJob:
  defaultUser:
    enabled: true
    role: Admin
    username: meisterpod
    email: email@example.com
    firstName: firstname
    lastName: lastname
    password: "placeholder"

webserver:
  startupProbe:
    failureThreshold: 30
    periodSeconds: 20

secret:
  - envName: AIRFLOW__WEBSERVER__SECRET_KEY
    secretName: airflow-webserver-secret
    secretKey: password

data:
  metadataSecretName: airflow-metadata-secret

dags:
  gitSync:
    enabled: true
    repo: git@github.com:mblaster00/weather-etl-pipeline-sur-airflow-k8s.git
    branch: main
    subPath: dags/
    sshKeySecret: airflow-gitsync-ssh

triggerer:
  enabled: false

postgresql:
  enabled: true
  auth:
    existingSecret: airflow-postgres-secret
    secretKeys:
      adminPasswordKey: password
    database: airflow
    username: postgres