executor: KubernetesExecutor

webserverSecretKeySecretName: airflow-webserver-secret-key
webserverSecretKeySecretKey: webserver-secret-key

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: username
    email: email@example.com
    firstName: firstname
    lastName: lastname
    password: "password"

secret:
  - envName: AIRFLOW__WEBSERVER__SECRET_KEY
    secretName: airflow-webserver-secret
    secretKey: password

data:
  metadataSecretName: airflow-metadata-secret

dags:
  gitSync:
    enabled: true
    repo: git@github.com:mblaster00/weather-etl-airflow.git
    branch: main
    subPath: dags/
    sshKeySecret: airflow-gitsync-ssh

postgresql:
  enabled: true
  auth:
    existingSecret: airflow-postgres-secret
    secretKeys:
      adminPasswordKey: password
    database: airflow
    username: postgres